version: '3.3'
services:
  web:
    image: httpd
    ports:
      - "80:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
    networks:
      - application

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - application

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports:
      - "5601:5601"
    networks:
      - elasticsearch

networks:
  elasticsearch:
    driver: bridge
  application:
    driver: bridge
